// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_heXAw6E7CzcPYZS9LwQVx2hC2I83BI',
    appId: '1:795883241493:web:c368ae4f98e6d434dc8e1c',
    messagingSenderId: '795883241493',
    projectId: 'whatsapp-clone-35992',
    authDomain: 'whatsapp-clone-35992.firebaseapp.com',
    storageBucket: 'whatsapp-clone-35992.appspot.com',
    measurementId: 'G-MMQX3JM2F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-h_LECmfQe3dORohkn6VxKLwjCWw9bVU',
    appId: '1:795883241493:android:185244be76a16f29dc8e1c',
    messagingSenderId: '795883241493',
    projectId: 'whatsapp-clone-35992',
    storageBucket: 'whatsapp-clone-35992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-QtzfAxBrernhldkwf3RQ0DcxmuEIW0',
    appId: '1:795883241493:ios:b3c2b492477deb00dc8e1c',
    messagingSenderId: '795883241493',
    projectId: 'whatsapp-clone-35992',
    storageBucket: 'whatsapp-clone-35992.appspot.com',
    iosBundleId: 'com.example.newWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV-QtzfAxBrernhldkwf3RQ0DcxmuEIW0',
    appId: '1:795883241493:ios:bb171ad692595473dc8e1c',
    messagingSenderId: '795883241493',
    projectId: 'whatsapp-clone-35992',
    storageBucket: 'whatsapp-clone-35992.appspot.com',
    iosBundleId: 'com.example.newWhatsappClone.RunnerTests',
  );
}
